"""
Game session routes.

POST /v1/games/chess/start   — start or restart a chess game
POST /v1/games/chess/move    — submit a move, get Koroki's response + commentary
GET  /v1/games/chess/state   — current board state
POST /v1/games/chess/resign  — resign the active game
POST /v1/games/decide        — visual-game decision cycle (Stage 2: she plays)

Commentary is generated by a self-call to /v1/chat with game_event_context set,
so it goes through the real brain with full personality.  defer_tts=True means
the TTS job is created but we discard it here (chess is text-only).

/games/decide is the captain's S3-structured play cycle (gaming-eyes ranking,
docs/master_queue.md): scene + rolling state doc in → STATE/DO/SAY out. Her
felt-state rides along, so her body colors her play — tired Koroki plays lazy.
"""
from __future__ import annotations

import base64
import logging
from ..nervous_system import on_activity_event
import uuid

import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from ..games.board_render import render_board_png
from ..games.chess import chess_engine, render_board, HAS_CHESS
from ..games.commentary import (
    build_chess_game_start_context,
    build_chess_move_context,
    build_chess_resign_context,
    build_grounding_retry_context,
    should_comment_on_move,
    ungrounded_chess_claims,
)
from shared.utils.config import get_settings

router = APIRouter()
logger = logging.getLogger("orchestrator.games")


async def _request_commentary(
    user_id: str,
    is_owner: bool,
    relationship_score: int,
    game_event_context: str,
) -> str:
    """Fire a /v1/chat call with game_event_context to get in-character streamer commentary."""
    settings = get_settings()
    url = f"{settings['services']['orchestrator']['url']}/v1/chat"
    try:
        async with httpx.AsyncClient(timeout=25.0) as client:
            resp = await client.post(url, json={
                "request_id": f"game_{uuid.uuid4().hex[:10]}",
                # The context MUST ride the message, marked as system voice. The old
                # placeholder "[chess]" left the 4B with zero context: the agent
                # prompt profile filters chess_event= facts entirely, so she was
                # improvising blind ("okay. think short", 2026-07-04). game_event_
                # context still goes along for the token budget + turn-non-persist.
                "message": f"[system] {game_event_context}",
                "defer_tts": True,
                "game_event_context": game_event_context,
                "user_context": {
                    "user_id": user_id,
                    "relationship_score": relationship_score,
                    "is_owner": is_owner,
                    "mode": "auto",
                    "platform": "discord",
                },
            })
            if resp.status_code == 200:
                return resp.json().get("text", "").strip()
    except Exception as exc:
        logger.warning("[Games] Commentary request failed: %s", exc)
    return ""


async def _grounded_commentary(
    user_id: str,
    is_owner: bool,
    relationship_score: int,
    context: str,
    *,
    in_check: bool,
    status: str,
) -> str:
    """Commentary with engine-verified chess claims: retry once on a false
    check/mate claim, drop the line if it still lies. Silence beats nonsense —
    the mechanical move header keeps the human informed either way."""
    commentary = await _request_commentary(user_id, is_owner, relationship_score, context)
    bad = ungrounded_chess_claims(commentary, in_check=in_check, status=status)
    if not bad:
        return commentary
    logger.info("[Games] ungrounded %s in commentary %r — retrying", bad, commentary[:80])
    retry = await _request_commentary(
        user_id, is_owner, relationship_score, build_grounding_retry_context(context, bad)
    )
    if retry and not ungrounded_chess_claims(retry, in_check=in_check, status=status):
        return retry
    logger.info("[Games] commentary still ungrounded (%r) — dropping the line", retry[:80])
    return ""


class ChessStartRequest(BaseModel):
    user_id: str = Field(..., min_length=1, max_length=64)
    is_owner: bool = False
    relationship_score: int = Field(default=0, ge=0, le=100)
    color: str = "white"  # "white" | "black"


class ChessMoveRequest(BaseModel):
    user_id: str = Field(..., min_length=1, max_length=64)
    is_owner: bool = False
    relationship_score: int = Field(default=0, ge=0, le=100)
    move: str = Field(..., min_length=1, max_length=12)


class ChessResignRequest(BaseModel):
    user_id: str = Field(..., min_length=1, max_length=64)
    is_owner: bool = False
    relationship_score: int = Field(default=0, ge=0, le=100)


@router.post("/games/chess/start")
async def chess_start(req: ChessStartRequest) -> dict:
    if not HAS_CHESS:
        raise HTTPException(status_code=503, detail="python-chess not installed (pip install chess)")

    # Clear any existing session first.
    chess_engine.end_session(req.user_id)
    color = req.color.lower() if req.color.lower() in ("white", "black") else "white"
    session = chess_engine.start_game(req.user_id, user_color=color)

    import chess as _chess  # local import to respect HAS_CHESS guard above
    first_koroki_move: str | None = None
    if session.user_color == _chess.BLACK:
        # User plays Black → Koroki (White) opens first.
        result = await chess_engine.make_koroki_move(session)
        first_koroki_move = result.get("koroki_move")

    context = build_chess_game_start_context(color)
    commentary = await _grounded_commentary(
        req.user_id, req.is_owner, req.relationship_score, context,
        in_check=False, status="active",
    )

    _png = render_board_png(session.board, session.user_color)
    return {
        "game_id": session.game_id,
        "user_color": color,
        "board_ascii": render_board(session.board, session.user_color),
        "board_png_b64": base64.b64encode(_png).decode() if _png else None,
        "board_fen": session.board.fen(),
        "first_koroki_move": first_koroki_move,
        "commentary": commentary,
        "status": "active",
    }


@router.post("/games/chess/move")
async def chess_move(req: ChessMoveRequest) -> dict:
    if not HAS_CHESS:
        raise HTTPException(status_code=503, detail="python-chess not installed (pip install chess)")

    result = await chess_engine.apply_user_move(req.user_id, req.move.strip())
    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])

    _status = str(result.get("status", "active"))
    if _status in ("checkmate", "stalemate", "draw"):
        _winner = result.get("winner")
        on_activity_event("chess_won" if _winner == "koroki" else "chess_lost")
    else:
        on_activity_event("chess_move")

    _move_num = int(result.get("move_number", 0))
    _in_check = bool(result.get("in_check", False))
    _status = str(result.get("status", "active"))

    _session = chess_engine.get_session(req.user_id)
    commentary = ""
    if should_comment_on_move(
        _status, _in_check, _move_num, notable=bool(result.get("koroki_move_notable"))
    ):
        context = build_chess_move_context(
            user_move=result.get("user_move"),
            koroki_move=result.get("koroki_move"),
            move_number=_move_num,
            in_check=_in_check,
            status=_status,
            koroki_move_desc=result.get("koroki_move_desc"),
            user_move_desc=result.get("user_move_desc"),
            threat=result.get("koroki_threat"),
            material=result.get("material_note"),
            avoid_lines=_session.recent_lines if _session else None,
        )
        commentary = await _grounded_commentary(
            req.user_id, req.is_owner, req.relationship_score, context,
            in_check=_in_check, status=_status,
        )
        if commentary and _session is not None:
            # Exact-repeat hard drop (watch-loop precedent) + rolling avoid window.
            if any(commentary.lower() == p.lower() for p in _session.recent_lines):
                logger.info("[Games] dropped exact repeat commentary: %r", commentary[:60])
                commentary = ""
            else:
                _session.recent_lines = (_session.recent_lines + [commentary])[-3:]
    result["commentary"] = commentary

    if _session is not None:
        _png = render_board_png(_session.board, _session.user_color)
        result["board_png_b64"] = base64.b64encode(_png).decode() if _png else None
    return result


@router.get("/games/chess/state")
async def chess_state(user_id: str) -> dict:
    if not HAS_CHESS:
        raise HTTPException(status_code=503, detail="python-chess not installed (pip install chess)")

    session = chess_engine.get_session(user_id)
    if not session:
        raise HTTPException(status_code=404, detail="no_active_game")

    _png = render_board_png(session.board, session.user_color)
    return {
        "game_id": session.game_id,
        "board_ascii": render_board(session.board, session.user_color),
        "board_png_b64": base64.b64encode(_png).decode() if _png else None,
        "board_fen": session.board.fen(),
        "move_history": session.move_history,
        "status": session.status,
        "is_users_turn": session.is_users_turn,
        "move_count": len(session.move_history),
    }


@router.post("/games/chess/resign")
async def chess_resign(req: ChessResignRequest) -> dict:
    if not HAS_CHESS:
        raise HTTPException(status_code=503, detail="python-chess not installed (pip install chess)")

    result = chess_engine.resign(req.user_id)
    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])

    context = build_chess_resign_context()
    commentary = await _grounded_commentary(
        req.user_id, req.is_owner, req.relationship_score, context,
        in_check=False, status="resigned",  # resignation is not a mate — don't let her claim one
    )
    result["commentary"] = commentary
    chess_engine.end_session(req.user_id)
    return result


# ---------------------------------------------------------------------------
# Visual game playing — the captain's decision cycle (Stage 2)
# ---------------------------------------------------------------------------

import re as _re

_STATE_RE = _re.compile(r"state\s*[:\-]\s*(progressing|blocked|regressed)", _re.I)
_DO_RE = _re.compile(
    r"do\s*[:\-]\s*(hold_click|click|press|hold|scroll|wait|look|push_goal|pop_goal|skill|save_skill|plan)\b\s*(.*)",
    _re.I,
)
_SAY_RE = _re.compile(r"say\s*[:\-]\s*(.+)", _re.I)


class GameDecideRequest(BaseModel):
    request_id: str = Field(default="", max_length=128)
    game: str = Field(..., min_length=1, max_length=120)
    objective: str = Field(default="explore and have fun", max_length=300)
    state_doc: str = Field(default="", max_length=1500)
    scene: str = Field(..., min_length=1, max_length=900)
    knowledge: str = Field(default="", max_length=700)
    # Blackboard exact-text layer (LIMBS wave 1, 2026-07-09): the words OCR
    # actually read on screen. The VLM scene is prose; click targets ground
    # on these — "click the store button" needs the word to exist.
    ocr_block: str = Field(default="", max_length=400)
    # Game Mind blocks (2026-07-05): the persistent-agency context — goal stack,
    # action->effect memory, numeric progress, failure lessons, saved skills.
    # Assembled by game_agent.py's GameMind; empty strings when absent.
    goals_block: str = Field(default="", max_length=700)
    recent_block: str = Field(default="", max_length=900)
    metrics_block: str = Field(default="", max_length=600)
    lessons_block: str = Field(default="", max_length=700)
    skills_block: str = Field(default="", max_length=400)
    # "play" = normal STATE/DO/SAY cycle; "curriculum" = the Voyager-style goal
    # review (pre-verified 2026-07-05: the 4B never pushes/pops goals inline —
    # meta-cognition needs its own call where it's the ONLY thing asked).
    mode: str = Field(default="play", max_length=16)


_GOAL_RE = _re.compile(r"goal_action\s*[:\-]\s*(keep|pop_then_push|pop|push)\b\s*(.*)", _re.I)
_GOAL_BARE_RE = _re.compile(r"^\s*(keep|pop_then_push|pop|push)\b\s*(.*)", _re.I | _re.M)


def parse_curriculum(raw: str) -> dict:
    """Parse the goal-review reply: KEEP / POP / PUSH <goal> / POP_THEN_PUSH <goal>.

    Tolerant of a missing GOAL_ACTION: prefix — the 4B answered a bare 'keep'
    on first live contact (2026-07-05)."""
    m = _GOAL_RE.search(raw) or _GOAL_BARE_RE.search(raw)
    if not m:
        return {"goal_action": "keep", "goal": ""}
    verb = m.group(1).lower()
    goal = m.group(2).strip().strip(".!")[:160]
    if verb in ("push", "pop_then_push") and not goal:
        return {"goal_action": "keep", "goal": ""}
    return {"goal_action": verb, "goal": goal}


def parse_decision(raw: str) -> dict:
    """Tolerant parse of the STATE/DO/SAY block into an executor action.

    Anything unparseable degrades to 'look' — she observes instead of acting
    on garbage. Pure function, contract-tested.
    """
    task_state = "progressing"
    m = _STATE_RE.search(raw)
    if m:
        task_state = m.group(1).lower()

    action: dict = {"type": "look"}
    m = _DO_RE.search(raw)
    if m:
        verb, rest = m.group(1).lower(), m.group(2).strip().strip(".!")
        if verb == "click" and rest:
            # She sometimes copies the option-list syntax into the target
            # ("click 'store' / scroll down") — keep only the first option,
            # strip quotes; pointing can't hit a menu of alternatives.
            target = rest.split("/")[0].strip().strip("'\"").strip()
            action = {"type": "click", "target": target[:120]} if target else {"type": "look"}
        elif verb == "press" and rest:
            action = {"type": "press", "key": rest.split()[0][:16]}
        elif verb == "hold" and rest:
            parts = rest.split()
            key = parts[0][:16]
            try:
                secs = float(parts[1])
            except (ValueError, IndexError):
                secs = 1.5
            action = {"type": "hold", "key": key, "seconds": secs}
        elif verb == "hold_click" and rest:
            # "hold_click the pump handle 3" — trailing number = seconds
            parts = rest.split("/")[0].strip().strip("'\"").split()
            secs = 1.5
            if len(parts) > 1:
                try:
                    secs = float(parts[-1])
                    parts = parts[:-1]
                except ValueError:
                    pass
            target = " ".join(parts).strip()
            action = ({"type": "hold_click", "target": target[:120], "seconds": secs}
                      if target else {"type": "look"})
        elif verb == "scroll":
            low = rest.lower()
            amount = 3 if "up" in low else -3
            action = {"type": "scroll", "amount": amount}
        elif verb == "wait":
            try:
                secs = float(rest.split()[0])
            except (ValueError, IndexError):
                secs = 2.0
            action = {"type": "wait", "seconds": secs}
        # Game Mind meta-actions — handled by the PlaySession, never by hands.
        elif verb == "push_goal" and rest:
            action = {"type": "push_goal", "goal": rest[:160]}
        elif verb == "pop_goal":
            action = {"type": "pop_goal"}
        elif verb == "skill" and rest:
            action = {"type": "skill", "name": rest.split()[0][:40]}
        elif verb == "save_skill" and rest:
            action = {"type": "save_skill", "name": rest.split()[0][:40]}
        # LIMBS W1.2: multi-step delegation to the motor planner ("plan open
        # the shop and buy the cheapest upgrade") — PlaySession expands it via
        # /v1/games/plan and executes the steps closed-loop.
        elif verb == "plan" and rest:
            action = {"type": "plan", "intent": rest[:200]}
        # 'look' (or empty rest for click/press) stays/observes

    say = ""
    m = _SAY_RE.search(raw)
    if m:
        say = m.group(1).strip()
        if "[silent]" in say.lower():
            say = ""

    return {"task_state": task_state, "action": action, "say": say}


# ── LIMBS W1.2: the motor planner (captain intent → schema-locked steps) ──

PLAN_STEP_VERBS = ("click", "press", "hold", "hold_click", "scroll_up", "scroll_down", "wait")

# The brain's /v1/plan locks generation to this schema at the logit level —
# a malformed plan cannot be emitted (lm-format-enforcer in .venv_brain2).
PLAN_SCHEMA = {
    "type": "object",
    "properties": {
        "steps": {
            "type": "array", "minItems": 1, "maxItems": 5,
            "items": {
                "type": "object",
                "properties": {
                    "verb": {"type": "string", "enum": list(PLAN_STEP_VERBS)},
                    "target": {"type": "string", "maxLength": 60},
                    "seconds": {"type": "number", "minimum": 0, "maximum": 8},
                },
                "required": ["verb", "target"],
            },
        },
        "abort_if": {"type": "string", "maxLength": 80},
    },
    "required": ["steps"],
}

_PLANNER_SYSTEM = (
    "You are the motor planner for a game-playing agent. Turn the captain's "
    "intent into 1-5 concrete UI steps. Rules: use ONLY elements visible in "
    "the on-screen text; durations go in the 'seconds' field, never in "
    "'target'; abort_if is a SHORT stop condition (example: 'a Robux purchase "
    "page appears'), never a copy of the screen text. Real-money rule: to "
    "close or escape a popup/offer/purchase page, the ONLY valid step is "
    "clicking its X or close button, or pressing escape — one single step, "
    "never click the offer itself and never click buy or purchase buttons. "
    'Example: intent "close this popup", screen "Special Offer! | Buy Now | X" '
    '-> {"steps": [{"verb": "click", "target": "X"}], "abort_if": "a purchase '
    'page opens"}. Output JSON only.'
)


def normalize_plan_step(step: dict) -> dict | None:
    """Planner step → executor action, or None to drop it.

    Encodes the first live-probe lessons (2026-07-09): the 4B sometimes puts a
    wait's duration in 'target', and durations must clamp to the hands' rails.
    Pure function, contract-tested.
    """
    verb = str(step.get("verb", "")).lower()
    target = str(step.get("target", "")).strip()
    secs = step.get("seconds")
    good_secs = float(secs) if isinstance(secs, (int, float)) and secs > 0 else None

    if verb in ("click", "hold_click"):
        if not target:
            return None
        action: dict = {"type": verb, "target": target[:120]}
        if verb == "hold_click":
            action["seconds"] = min(good_secs or 1.5, 8.0)
        return action
    if verb == "press":
        return {"type": "press", "key": target.split()[0][:16]} if target else None
    if verb == "hold":
        if not target:
            return None
        return {"type": "hold", "key": target.split()[0][:16],
                "seconds": min(good_secs or 1.5, 8.0)}
    if verb in ("scroll_up", "scroll_down"):
        return {"type": "scroll", "amount": 3 if verb == "scroll_up" else -3}
    if verb == "wait":
        s = good_secs
        if s is None:
            try:
                s = float(target)  # probe lesson: duration lands in target
            except ValueError:
                s = 2.0
        return {"type": "wait", "seconds": max(0.5, min(s, 8.0))}
    return None


class GamePlanRequest(BaseModel):
    request_id: str = Field(default="", max_length=128)
    game: str = Field(..., min_length=1, max_length=120)
    intent: str = Field(..., min_length=1, max_length=200)
    ocr_block: str = Field(default="", max_length=400)
    knowledge: str = Field(default="", max_length=700)


@router.post("/games/plan")
async def game_plan(req: GamePlanRequest) -> dict:
    """Captain intent → executable closed-loop steps (LIMBS W1.2)."""
    settings = get_settings()
    plan_url = settings["services"]["brain"]["url"] + "/v1/plan"

    knowledge = f"\ngame notes: {req.knowledge}" if req.knowledge else ""
    message = (
        f"game: {req.game}{knowledge}\n"
        f"intent: {req.intent}\n"
        f"exact text on screen (OCR): {req.ocr_block or '(nothing read)'}\n"
        "plan the steps."
    )
    payload = {
        "request_id": req.request_id or f"plan_{uuid.uuid4().hex[:8]}",
        "system": _PLANNER_SYSTEM,
        "message": message[:4000],
        "json_schema": PLAN_SCHEMA,
        "max_new_tokens": 220,
    }
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.post(plan_url, json=payload)
    except httpx.HTTPError as exc:
        raise HTTPException(status_code=502, detail=f"planner unreachable: {exc}")
    if resp.status_code != 200:
        # 501 = transformers rollback engine (no filters) — caller degrades to
        # single-action decides; anything else is a real failure.
        raise HTTPException(status_code=502,
                            detail=f"planner unavailable ({resp.status_code})")
    plan_obj = resp.json().get("plan") or {}
    steps = [s for s in (normalize_plan_step(x) for x in plan_obj.get("steps") or [])
             if s is not None]
    return {
        "request_id": req.request_id,
        "steps": steps,
        "abort_if": str(plan_obj.get("abort_if") or "")[:80],
    }


@router.post("/games/decide")
async def game_decide(req: GameDecideRequest) -> dict:
    """One play-cycle decision: scene + state in, STATE/DO/SAY out."""
    settings = get_settings()
    brain_url = settings["services"]["brain"]["url"] + "/v1/generate"

    knowledge = f"\ngame notes: {req.knowledge}" if req.knowledge else ""
    ocr = f"\nexact text on screen (OCR): {req.ocr_block}" if req.ocr_block else ""
    state_doc = req.state_doc or "(the session just started)"
    # Game Mind blocks lead the message — goals before pixels, so she pursues
    # instead of describes (the whole point of the 2026-07-05 agency arc).
    mind_parts = [b for b in (req.goals_block, req.metrics_block, req.recent_block,
                              req.lessons_block, req.skills_block) if b]
    mind = ("\n".join(mind_parts) + "\n") if mind_parts else ""

    if req.mode == "strategy":
        # The optimizer's eye (owner 2026-07-05: "look around, evaluate, make
        # things efficient" — she ignored 32% demand instead of lowering price).
        # Output persists as the STRATEGY block in every subsequent decide.
        message = (
            f"[you're playing '{req.game}'. study break — no move this turn.\n"
            f"{mind}"
            f"on screen: {req.scene}{ocr}]\n"
            "think like an optimizer: look at EVERY number and control on screen. "
            "what is inefficient or being wasted right now? what mechanic are you "
            "ignoring? (the kind of thinking: unsold inventory piling up = price "
            "too high; low demand % = lower the price; idle money = an upgrade "
            "is affordable.)\n"
            "reply with EXACTLY three short lines:\n"
            "NOTICED: <the most important number/mechanic you were ignoring>\n"
            "INEFFICIENCY: <what's suboptimal right now>\n"
            "PLAN: <the concrete next 2-3 moves to fix it>"
        )
    elif req.mode == "curriculum":
        # Goal review is the ONLY question — meta-cognition gets its own call.
        # GOAL_STATUS forces the numeric comparison BEFORE the verdict — first
        # live contact showed the 4B answering "keep" on a clearly-completed
        # goal because nothing made it look at the numbers (2026-07-05).
        message = (
            f"[you're playing '{req.game}'. quick goal check, no move this turn.\n"
            f"{mind}"
            f"latest on screen: {req.scene}]\n"
            "rules: if the metrics show the current goal's condition is met -> pop "
            "(or pop_then_push with the next milestone). if there is NO current "
            "goal above -> you MUST push one small concrete next milestone toward "
            "the FINAL GOAL. otherwise keep. a milestone is an IN-GAME step that "
            "names something visible on the screen right now (a button, a number "
            "to reach, a thing to buy) — never anything about yourself or your "
            "systems.\n"
            "reply in EXACTLY this format and nothing else:\n"
            "GOAL_STATUS: <compare the current goal to the metrics in a few words>\n"
            "GOAL_ACTION: keep / pop / push <next milestone> / pop_then_push <next milestone>"
        )
    else:
        message = None  # built below (play mode)
    if message is None:
        message = (
        f"[you're playing '{req.game}' live on stream. objective: {req.objective}.{knowledge}\n"
        f"{mind}"
        f"what's happened so far: {state_doc}\n"
        f"on screen right now: {req.scene}{ocr}]\n"
        "decide your next move — the one that best advances your CURRENT GOAL. "
        "hard rule: NEVER click anything that leads outside the game or toward "
        "real money — merch, gift shops, t-shirts, app store links, donate/"
        "subscribe buttons, checkout pages. real-world purchases are not part "
        "of any game.\n"
        "reply in EXACTLY this format and nothing else:\n"
        "STATE: progressing or blocked or regressed\n"
        "DO: click <thing on the screen> / hold_click <thing> <seconds> "
        "(keep the mouse held on it) / press <key> / hold <key> <seconds> "
        "(hold w to walk forward) / scroll up / scroll down / wait / look / "
        "plan <a multi-step goal in plain words — the motor planner breaks it "
        "into precise steps> / "
        "push_goal <new sub-goal you'll work on now> / pop_goal (current goal is DONE) / "
        "skill <saved skill name> / save_skill <name for the recent working sequence>\n"
        "SAY: one short line to your viewers, or [silent]\n"
        "your reply MUST start with the word STATE:"
    )

    felt = None
    try:
        from ..body.interoception import get_felt_state
        felt = get_felt_state().to_prompt_block() or None
    except Exception:
        pass

    # Thinking ON for game reasoning (2026-07-05, owner: "she lacks a thinking
    # engine — demand is 32% and she never considers lowering the price").
    # Qwen3's <think> phase reasons about the position before the format lines;
    # the brain strips the think block, and _DO_RE finds the format regardless.
    # Budget covers thinking + answer; cycles are ~10s apart so latency fits.
    payload = {
        "request_id": req.request_id or f"decide_{uuid.uuid4().hex[:8]}",
        "message": message[:5500],  # brain cap raised to 6000 (2026-07-05)
        "user_context": {
            "user_id": "game_session",
            "relationship_score": 100,
            "is_owner": True,
            "mode": "owner",
            "platform": "discord",
        },
        "max_new_tokens": 96 if req.mode == "curriculum" else 352,
        "enable_thinking": req.mode != "curriculum",
        "enable_tools": False,
        "felt_state": felt,
    }
    try:
        async with httpx.AsyncClient(timeout=45.0) as client:
            resp = await client.post(brain_url, json=payload)
            resp.raise_for_status()
            raw = str(resp.json().get("text") or "").strip()

            # Format retry: long mind-block prompts make the 4B drop the template
            # and answer in prose (a live session froze on 'look' this way,
            # 2026-07-05 — and v1 of this retry never fired because its gate
            # looked for the WORD 'do', which prose contains). Gate on the real
            # parse regex, and retry with a COMPACT prompt — short prompts
            # produced clean format all day; length is what breaks it.
            if req.mode == "play" and not _DO_RE.search(raw):
                payload["message"] = (
                    f"[playing '{req.game}'. current goal: "
                    f"{(req.goals_block.splitlines()[-1] if req.goals_block else req.objective)[:140]}\n"
                    f"on screen: {req.scene[:500]}]\n"
                    "reply with ONLY these three lines:\n"
                    "STATE: progressing or blocked\n"
                    "DO: click <thing> / press <key> / scroll up / scroll down / wait / look\n"
                    "SAY: one short line or [silent]"
                )
                payload["request_id"] += "_r"
                resp = await client.post(brain_url, json=payload)
                resp.raise_for_status()
                retry_raw = str(resp.json().get("text") or "").strip()
                if _DO_RE.search(retry_raw):
                    raw = retry_raw
    except httpx.HTTPError as exc:
        logger.warning("[Games] decide brain call failed: %s", exc)
        raise HTTPException(status_code=502, detail=f"brain unavailable: {exc}")

    if req.mode == "strategy":
        logger.info("[Games] strategy(%s): %r", req.game, raw[:120])
        return {"strategy": raw[:500], "raw": raw[:500]}

    if req.mode == "curriculum":
        review = parse_curriculum(raw)
        review["raw"] = raw[:400]
        logger.info("[Games] curriculum(%s): %s %r", req.game,
                    review["goal_action"], review["goal"][:60])
        return review

    decision = parse_decision(raw)
    decision["raw"] = raw[:400]
    logger.info("[Games] decide(%s): state=%s action=%s say=%r",
                req.game, decision["task_state"], decision["action"],
                decision["say"][:60])
    return decision
