"""
Game session routes.

POST /v1/games/chess/start   — start or restart a chess game
POST /v1/games/chess/move    — submit a move, get Koroki's response + commentary
GET  /v1/games/chess/state   — current board state
POST /v1/games/chess/resign  — resign the active game
POST /v1/games/decide        — visual-game decision cycle (Stage 2: she plays)

Commentary is generated by a self-call to /v1/chat with game_event_context set,
so it goes through the real brain with full personality.  defer_tts=True means
the TTS job is created but we discard it here (chess is text-only).

/games/decide is the captain's S3-structured play cycle (gaming-eyes ranking,
docs/master_queue.md): scene + rolling state doc in → STATE/DO/SAY out. Her
felt-state rides along, so her body colors her play — tired Koroki plays lazy.
"""
from __future__ import annotations

import base64
import logging
from ..nervous_system import on_activity_event
import uuid

import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from ..games.board_render import render_board_png
from ..games.chess import chess_engine, render_board, HAS_CHESS
from ..games.commentary import (
    build_chess_game_start_context,
    build_chess_move_context,
    build_chess_resign_context,
    build_grounding_retry_context,
    should_comment_on_move,
    ungrounded_chess_claims,
)
from shared.utils.config import get_settings

router = APIRouter()
logger = logging.getLogger("orchestrator.games")


async def _request_commentary(
    user_id: str,
    is_owner: bool,
    relationship_score: int,
    game_event_context: str,
) -> str:
    """Fire a /v1/chat call with game_event_context to get in-character streamer commentary."""
    settings = get_settings()
    url = f"{settings['services']['orchestrator']['url']}/v1/chat"
    try:
        async with httpx.AsyncClient(timeout=25.0) as client:
            resp = await client.post(url, json={
                "request_id": f"game_{uuid.uuid4().hex[:10]}",
                # The context MUST ride the message, marked as system voice. The old
                # placeholder "[chess]" left the 4B with zero context: the agent
                # prompt profile filters chess_event= facts entirely, so she was
                # improvising blind ("okay. think short", 2026-07-04). game_event_
                # context still goes along for the token budget + turn-non-persist.
                "message": f"[system] {game_event_context}",
                "defer_tts": True,
                "game_event_context": game_event_context,
                "user_context": {
                    "user_id": user_id,
                    "relationship_score": relationship_score,
                    "is_owner": is_owner,
                    "mode": "auto",
                    "platform": "discord",
                },
            })
            if resp.status_code == 200:
                return resp.json().get("text", "").strip()
    except Exception as exc:
        logger.warning("[Games] Commentary request failed: %s", exc)
    return ""


async def _grounded_commentary(
    user_id: str,
    is_owner: bool,
    relationship_score: int,
    context: str,
    *,
    in_check: bool,
    status: str,
) -> str:
    """Commentary with engine-verified chess claims: retry once on a false
    check/mate claim, drop the line if it still lies. Silence beats nonsense —
    the mechanical move header keeps the human informed either way."""
    commentary = await _request_commentary(user_id, is_owner, relationship_score, context)
    bad = ungrounded_chess_claims(commentary, in_check=in_check, status=status)
    if not bad:
        return commentary
    logger.info("[Games] ungrounded %s in commentary %r — retrying", bad, commentary[:80])
    retry = await _request_commentary(
        user_id, is_owner, relationship_score, build_grounding_retry_context(context, bad)
    )
    if retry and not ungrounded_chess_claims(retry, in_check=in_check, status=status):
        return retry
    logger.info("[Games] commentary still ungrounded (%r) — dropping the line", retry[:80])
    return ""


class ChessStartRequest(BaseModel):
    user_id: str = Field(..., min_length=1, max_length=64)
    is_owner: bool = False
    relationship_score: int = Field(default=0, ge=0, le=100)
    color: str = "white"  # "white" | "black"


class ChessMoveRequest(BaseModel):
    user_id: str = Field(..., min_length=1, max_length=64)
    is_owner: bool = False
    relationship_score: int = Field(default=0, ge=0, le=100)
    move: str = Field(..., min_length=1, max_length=12)


class ChessResignRequest(BaseModel):
    user_id: str = Field(..., min_length=1, max_length=64)
    is_owner: bool = False
    relationship_score: int = Field(default=0, ge=0, le=100)


@router.post("/games/chess/start")
async def chess_start(req: ChessStartRequest) -> dict:
    if not HAS_CHESS:
        raise HTTPException(status_code=503, detail="python-chess not installed (pip install chess)")

    # Clear any existing session first.
    chess_engine.end_session(req.user_id)
    color = req.color.lower() if req.color.lower() in ("white", "black") else "white"
    session = chess_engine.start_game(req.user_id, user_color=color)

    import chess as _chess  # local import to respect HAS_CHESS guard above
    first_koroki_move: str | None = None
    if session.user_color == _chess.BLACK:
        # User plays Black → Koroki (White) opens first.
        result = await chess_engine.make_koroki_move(session)
        first_koroki_move = result.get("koroki_move")

    context = build_chess_game_start_context(color)
    commentary = await _grounded_commentary(
        req.user_id, req.is_owner, req.relationship_score, context,
        in_check=False, status="active",
    )

    _png = render_board_png(session.board, session.user_color)
    return {
        "game_id": session.game_id,
        "user_color": color,
        "board_ascii": render_board(session.board, session.user_color),
        "board_png_b64": base64.b64encode(_png).decode() if _png else None,
        "board_fen": session.board.fen(),
        "first_koroki_move": first_koroki_move,
        "commentary": commentary,
        "status": "active",
    }


@router.post("/games/chess/move")
async def chess_move(req: ChessMoveRequest) -> dict:
    if not HAS_CHESS:
        raise HTTPException(status_code=503, detail="python-chess not installed (pip install chess)")

    result = await chess_engine.apply_user_move(req.user_id, req.move.strip())
    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])

    _status = str(result.get("status", "active"))
    if _status in ("checkmate", "stalemate", "draw"):
        _winner = result.get("winner")
        on_activity_event("chess_won" if _winner == "koroki" else "chess_lost")
    else:
        on_activity_event("chess_move")

    _move_num = int(result.get("move_number", 0))
    _in_check = bool(result.get("in_check", False))
    _status = str(result.get("status", "active"))

    _session = chess_engine.get_session(req.user_id)
    commentary = ""
    if should_comment_on_move(
        _status, _in_check, _move_num, notable=bool(result.get("koroki_move_notable"))
    ):
        context = build_chess_move_context(
            user_move=result.get("user_move"),
            koroki_move=result.get("koroki_move"),
            move_number=_move_num,
            in_check=_in_check,
            status=_status,
            koroki_move_desc=result.get("koroki_move_desc"),
            user_move_desc=result.get("user_move_desc"),
            threat=result.get("koroki_threat"),
            material=result.get("material_note"),
            avoid_lines=_session.recent_lines if _session else None,
        )
        commentary = await _grounded_commentary(
            req.user_id, req.is_owner, req.relationship_score, context,
            in_check=_in_check, status=_status,
        )
        if commentary and _session is not None:
            # Exact-repeat hard drop (watch-loop precedent) + rolling avoid window.
            if any(commentary.lower() == p.lower() for p in _session.recent_lines):
                logger.info("[Games] dropped exact repeat commentary: %r", commentary[:60])
                commentary = ""
            else:
                _session.recent_lines = (_session.recent_lines + [commentary])[-3:]
    result["commentary"] = commentary

    if _session is not None:
        _png = render_board_png(_session.board, _session.user_color)
        result["board_png_b64"] = base64.b64encode(_png).decode() if _png else None
    return result


@router.get("/games/chess/state")
async def chess_state(user_id: str) -> dict:
    if not HAS_CHESS:
        raise HTTPException(status_code=503, detail="python-chess not installed (pip install chess)")

    session = chess_engine.get_session(user_id)
    if not session:
        raise HTTPException(status_code=404, detail="no_active_game")

    _png = render_board_png(session.board, session.user_color)
    return {
        "game_id": session.game_id,
        "board_ascii": render_board(session.board, session.user_color),
        "board_png_b64": base64.b64encode(_png).decode() if _png else None,
        "board_fen": session.board.fen(),
        "move_history": session.move_history,
        "status": session.status,
        "is_users_turn": session.is_users_turn,
        "move_count": len(session.move_history),
    }


@router.post("/games/chess/resign")
async def chess_resign(req: ChessResignRequest) -> dict:
    if not HAS_CHESS:
        raise HTTPException(status_code=503, detail="python-chess not installed (pip install chess)")

    result = chess_engine.resign(req.user_id)
    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])

    context = build_chess_resign_context()
    commentary = await _grounded_commentary(
        req.user_id, req.is_owner, req.relationship_score, context,
        in_check=False, status="resigned",  # resignation is not a mate — don't let her claim one
    )
    result["commentary"] = commentary
    chess_engine.end_session(req.user_id)
    return result


# ---------------------------------------------------------------------------
# Visual game playing — the captain's decision cycle (Stage 2)
# ---------------------------------------------------------------------------

import re as _re

_STATE_RE = _re.compile(r"state\s*[:\-]\s*(progressing|blocked|regressed)", _re.I)
_DO_RE = _re.compile(r"do\s*[:\-]\s*(click|press|hold|scroll|wait|look)\b\s*(.*)", _re.I)
_SAY_RE = _re.compile(r"say\s*[:\-]\s*(.+)", _re.I)


class GameDecideRequest(BaseModel):
    request_id: str = Field(default="", max_length=128)
    game: str = Field(..., min_length=1, max_length=120)
    objective: str = Field(default="explore and have fun", max_length=300)
    state_doc: str = Field(default="", max_length=1500)
    scene: str = Field(..., min_length=1, max_length=900)
    knowledge: str = Field(default="", max_length=700)


def parse_decision(raw: str) -> dict:
    """Tolerant parse of the STATE/DO/SAY block into an executor action.

    Anything unparseable degrades to 'look' — she observes instead of acting
    on garbage. Pure function, contract-tested.
    """
    task_state = "progressing"
    m = _STATE_RE.search(raw)
    if m:
        task_state = m.group(1).lower()

    action: dict = {"type": "look"}
    m = _DO_RE.search(raw)
    if m:
        verb, rest = m.group(1).lower(), m.group(2).strip().strip(".!")
        if verb == "click" and rest:
            action = {"type": "click", "target": rest[:120]}
        elif verb == "press" and rest:
            action = {"type": "press", "key": rest.split()[0][:16]}
        elif verb == "hold" and rest:
            parts = rest.split()
            key = parts[0][:16]
            try:
                secs = float(parts[1])
            except (ValueError, IndexError):
                secs = 1.5
            action = {"type": "hold", "key": key, "seconds": secs}
        elif verb == "scroll":
            low = rest.lower()
            amount = 3 if "up" in low else -3
            action = {"type": "scroll", "amount": amount}
        elif verb == "wait":
            try:
                secs = float(rest.split()[0])
            except (ValueError, IndexError):
                secs = 2.0
            action = {"type": "wait", "seconds": secs}
        # 'look' (or empty rest for click/press) stays/observes

    say = ""
    m = _SAY_RE.search(raw)
    if m:
        say = m.group(1).strip()
        if "[silent]" in say.lower():
            say = ""

    return {"task_state": task_state, "action": action, "say": say}


@router.post("/games/decide")
async def game_decide(req: GameDecideRequest) -> dict:
    """One play-cycle decision: scene + state in, STATE/DO/SAY out."""
    settings = get_settings()
    brain_url = settings["services"]["brain"]["url"] + "/v1/generate"

    knowledge = f"\ngame notes: {req.knowledge}" if req.knowledge else ""
    state_doc = req.state_doc or "(the session just started)"
    message = (
        f"[you're playing '{req.game}' live on stream. objective: {req.objective}.{knowledge}\n"
        f"what's happened so far: {state_doc}\n"
        f"on screen right now: {req.scene}]\n"
        "decide your next move. reply in EXACTLY this format and nothing else:\n"
        "STATE: progressing or blocked or regressed\n"
        "DO: click <thing on the screen> / press <key> / hold <key> <seconds> "
        "(hold w to walk forward) / scroll up / scroll down / wait / look\n"
        "SAY: one short line to your viewers, or [silent]"
    )

    felt = None
    try:
        from ..body.interoception import get_felt_state
        felt = get_felt_state().to_prompt_block() or None
    except Exception:
        pass

    payload = {
        "request_id": req.request_id or f"decide_{uuid.uuid4().hex[:8]}",
        "message": message[:2000],
        "user_context": {
            "user_id": "game_session",
            "relationship_score": 100,
            "is_owner": True,
            "mode": "owner",
            "platform": "discord",
        },
        "max_new_tokens": 96,
        "enable_thinking": False,
        "enable_tools": False,
        "felt_state": felt,
    }
    try:
        async with httpx.AsyncClient(timeout=45.0) as client:
            resp = await client.post(brain_url, json=payload)
            resp.raise_for_status()
            raw = str(resp.json().get("text") or "").strip()
    except httpx.HTTPError as exc:
        logger.warning("[Games] decide brain call failed: %s", exc)
        raise HTTPException(status_code=502, detail=f"brain unavailable: {exc}")

    decision = parse_decision(raw)
    decision["raw"] = raw[:400]
    logger.info("[Games] decide(%s): state=%s action=%s say=%r",
                req.game, decision["task_state"], decision["action"],
                decision["say"][:60])
    return decision
